fix(deployment): Update scipts and configs
Signed-off-by: Muhammad Naufal <me@falkia34.dev>

diff --git a/deployment/healthcheck b/deployment/healthcheck
--- a/deployment/healthcheck
+++ b/deployment/healthcheck
@@ -1,19 +1,36 @@
 #!/usr/bin/env sh
 
+# Taken from https://github.com/exaco/laravel-octane-dockerfile
+
 set -e
 
 container_mode=${CONTAINER_MODE:-"server"}
 
-if [ ${container_mode} = "server" ]; then
-    php artisan octane:status
-elif [ ${container_mode} = "horizon" ]; then
-    php artisan horizon:status
-elif [ ${container_mode} = "reverb" ]; then
-    supervisorctl status reverb:reverb_00
-elif [ ${container_mode} = "scheduler" ]; then
-    supervisorctl status scheduler:scheduler_00
-elif [ ${container_mode} = "worker" ]; then
-    supervisorctl status worker:worker_00
+if [ "${container_mode}" = "server" ]; then
+    php "${ROOT}/artisan" octane:status
+elif [ "${container_mode}" = "horizon" ]; then
+    php "${ROOT}/artisan" horizon:status
+elif [ "${container_mode}" = "scheduler" ]; then
+    if [ "$(supervisorctl status scheduler:scheduler_0 | awk '{print tolower($2)}')" = "running" ]; then
+        exit 0
+    else
+        echo "Healthcheck failed."
+        exit 1
+    fi
+elif [ "${container_mode}" = "reverb" ]; then
+    if [ "$(supervisorctl status reverb:reverb_0 | awk '{print tolower($2)}')" = "running" ]; then
+        exit 0
+    else
+        echo "Healthcheck failed."
+        exit 1
+    fi
+elif [ "${container_mode}" = "worker" ]; then
+    if [ "$(supervisorctl status worker:worker_0 | awk '{print tolower($2)}')" = "running" ]; then
+        exit 0
+    else
+        echo "Healthcheck failed."
+        exit 1
+    fi
 else
     echo "Container mode mismatched."
     exit 1
